#!/usr/bin/env bash
set -e
IFS=$'\t\n'

# sane defaults
SELE_VER="2"
CHROME_START_COUNT="1"
FIREFOX_START_COUNT="1"
WITH_VIDEOS="true"
BUILD_NUMBER="0"
status=101 #assumed it failed unless proved wrong
# to count minutes of usage
start_time=$(date +%s)

TOOLS_DIR="/tools"

# Exit all child processes properly
shutdown () {
  echo ""
  echo "-----------------"
  echo "--- TESTS END ---"
  echo "-----------------"

  # shutdown tests if still running
  echo "INFO: Shutting down the test command..."
  docker stop ${TEST_CONTAINER} >/dev/null 2>&1 || true
  docker rm ${TEST_CONTAINER} >/dev/null 2>&1 || true

  # shutdown selenium
  echo "INFO: Shutting down selenium..."
  if [ "${WITH_VIDEOS}" == "true" ]; then
      mkdir -p ./videos
      docker cp ${SEL_CONTAINER}:/home/seluser/videos/. videos
  fi
  curl -sSL "https://raw.githubusercontent.com/dosel/t/i/p" | bash -s stop
  if [ "${WITH_VIDEOS}" == "true" ]; then
      if ! ls -la ./videos/; then
          echo "WARN: Videos should but were not transferred!" >&2
      fi
  fi

  echo "-- RESULT: Tests exit code=${status}"

  # give correct feedback
  exit ${status}
}

# Run function shutdown() when this process a killer signal
trap shutdown SIGHUP SIGTERM SIGINT

# In OSX install gtimeout through
#   brew install coreutils
function mtimeout() {
    if [ "$(uname -s)" = 'Darwin' ]; then
        gtimeout "$@"
    else
        timeout "$@"
    fi
}

# Actively waits for Zalenium to fully starts
# you can copy paste this in your Jenkins scripts
WaitVideosTransfered()
{
    while ! ls ./videos/* >/dev/null 2>&1; do
        echo -n '.'
        sleep 0.2
    done
}
export -f WaitVideosTransfered

# parse cli options http://stackoverflow.com/a/14203146/511069
for i in "$@"; do
    case $i in
        -s=*|--selenium=*)
        SELE_VER="${i#*=}"
        shift # past argument=value
        ;;
        -c=*|--chrome-count=*)
        CHROME_START_COUNT="${i#*=}"
        shift # past argument=value
        ;;
        -f=*|--firefox-count=*)
        FIREFOX_START_COUNT="${i#*=}"
        shift # past argument=value
        ;;
        --no-videos)
        WITH_VIDEOS="false"
        shift # past argument with no value
        ;;
        *)
                # unknown option
        ;;
    esac
done

SEL_CONTAINER="zalenium"
TEST_CONTAINER="test_${BUILD_NUMBER}"

if [ $# -lt 1 ]; then
    echo "Usage:  $0 [--selenium=2] [--chrome-count=1] [--firefox-count=1] <toolchain> [<toolchain-docker-opts>] -- <toolchain-command>" >&2
    echo "    Simple example:   $0 :toolchain-frontend -- gulp ui-test" >&2
    echo "    Advanced example: $0 --chrome-count=2 --firefox-count=2 :toolchain-frontend -- gulp ui-test" >&2
    #usage error arbitrary error number
    status=202
    exit $status
fi

TEST_DOCKER_IMAGE=$1
# remove first 1 args, we saved them leaving us with docker opts and command for the run tool
shift 1

# clean-up old Docker container
docker stop ${SEL_CONTAINER} 2>/dev/null || true
docker rm -fv ${SEL_CONTAINER} 2>/dev/null || true
# clean-up old Docker containers
docker rm -ff /test_0 2>/dev/null || true
docker rm -ff test_0 2>/dev/null || true

# Pull the toolchain so doesn't take test running time
${TOOLS_DIR}/run ${TEST_DOCKER_IMAGE} -- \
echo "Pull the toolchain so doesn't take testing time"

echo "INFO: Starting Selenium..."
export VIDEO=${WITH_VIDEOS}
curl -sSL "https://raw.githubusercontent.com/dosel/t/i/p" | bash -s ${SELE_VER} start

# wait
sleep 0.5
docker logs ${SEL_CONTAINER}

if [ "${WITH_VIDEOS}" == "true" ]; then
    docker exec zalenium mkdir -p /home/seluser/videos/
fi

start_time=$(date +%s)

# execute real command
echo ""
echo "-------------------"
echo "--- TESTS START ---"
echo "-------------------" && echo ""

# set +e
${TOOLS_DIR}/run ${TEST_DOCKER_IMAGE} \
  --name=${TEST_CONTAINER} \
  --net=container:${SEL_CONTAINER} \
  -e SELENIUM_URL="http://localhost:4444/wd/hub" \
  $@ && status=$? || status=$?

if [ "${WITH_VIDEOS}" == "true" ]; then
    if ! mtimeout --foreground "40s" bash -c WaitVideosTransfered; then
        echo "WARN: Failed while waiting for video files to exist."
    fi
fi

shutdown
